language: node_js
# version number of nodejs
node_js:
  - "18"
dist: trusty
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
    - client/node_modules

install:
  # installing deps
  - npm install
  # installing react deps and starting the server up
  - npm run build
# starting up the server and run some number of tests
script:
  # nohup (no hangup): if the shell is closed, dont kill anything this command creates
  # & will run the command in a subshell(background mode)
  # it's also called as background process
  - nohup npm run start &
  # wait for 3 seconds to start the server before running the tests
  - sleep 3
  - npm run test
